# Generated by Django 2.0.5 on 2018-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default='2018-05-30 21:09:20'),
        ),
    ]
