# Generated by Django 2.0.5 on 2018-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('uemail', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=40)),
                ('uphoto', models.ImageField(default='/static/media/user_info/default.jpg', null=True, upload_to='media/user_info/')),
            ],
        ),
    ]
