# Generated by Django 2.0.5 on 2018-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
